In [86]:
import pandas as pd
import numpy as np
import glob

In [87]:
a = enumerate(file_list)
file_list = glob.glob('*.xlsx')

In [88]:
a = []
for i, current_file in enumerate(file_list): 
    readingx = pd.read_excel(current_file, sheet_name = '1')
    print(current_file , i)
    a.append(np.asarray(readingx['x']))

b = []
for i, current_file in enumerate(file_list): 
    readingy = pd.read_excel(current_file, sheet_name = '1')
    print(current_file , i)
    b.append(np.asarray(readingy['y']))

c = []
for i, current_file in enumerate(file_list): 
    readingz = pd.read_excel(current_file, sheet_name = '1')
    print(current_file , i)
    c.append(np.asarray(readingz['z']))
    
d = []
for i, current_file in enumerate(file_list): 
    readingcw = pd.read_excel(current_file, sheet_name = '2')
    print(current_file , i)
    d.append(np.asarray(readingcw['cw']))
    
e = []
for i, current_file in enumerate(file_list): 
    readingch = pd.read_excel(current_file, sheet_name = '2')
    print(current_file , i)
    e.append(np.asarray(readingch['ch']))
    
f = []
for i, current_file in enumerate(file_list): 
    readingcd = pd.read_excel(current_file, sheet_name = '2')
    print(current_file , i)
    f.append(np.asarray(readingcd['cd']))
    
g = []
for i, current_file in enumerate(file_list): 
    readinggw = pd.read_excel(current_file, sheet_name = '2')
    print(current_file , i)
    g.append(np.asarray(readinggw['gw']))
    
h = []
for i, current_file in enumerate(file_list): 
    readinggd = pd.read_excel(current_file, sheet_name = '2')
    print(current_file , i)
    h.append(np.asarray(readinggd['gd']))
    
j = []
for i, current_file in enumerate(file_list): 
    readingdisp = pd.read_excel(current_file, sheet_name = '2')
    print(current_file , i)
    h.append(np.asarray(readinggd['disp']))
    
k = []
for i, current_file in enumerate(file_list): 
    readingangle = pd.read_excel(current_file, sheet_name = '2')
    print(current_file , i)
    k.append(np.asarray(readingangle['rotation']))

surface0.xlsx 0
surface1.xlsx 1
surface2.xlsx 2
surface3.xlsx 3
surface4.xlsx 4
surface5.xlsx 5
surface6.xlsx 6
surface7.xlsx 7
surface8.xlsx 8
surface0.xlsx 0
surface1.xlsx 1
surface2.xlsx 2
surface3.xlsx 3
surface4.xlsx 4
surface5.xlsx 5
surface6.xlsx 6
surface7.xlsx 7
surface8.xlsx 8
surface0.xlsx 0
surface1.xlsx 1
surface2.xlsx 2
surface3.xlsx 3
surface4.xlsx 4
surface5.xlsx 5
surface6.xlsx 6
surface7.xlsx 7
surface8.xlsx 8
surface0.xlsx 0
surface1.xlsx 1
surface2.xlsx 2
surface3.xlsx 3
surface4.xlsx 4
surface5.xlsx 5
surface6.xlsx 6
surface7.xlsx 7
surface8.xlsx 8
surface0.xlsx 0
surface1.xlsx 1
surface2.xlsx 2
surface3.xlsx 3
surface4.xlsx 4
surface5.xlsx 5
surface6.xlsx 6
surface7.xlsx 7
surface8.xlsx 8
surface0.xlsx 0
surface1.xlsx 1
surface2.xlsx 2
surface3.xlsx 3
surface4.xlsx 4
surface5.xlsx 5
surface6.xlsx 6
surface7.xlsx 7
surface8.xlsx 8
surface0.xlsx 0
surface1.xlsx 1
surface2.xlsx 2
surface3.xlsx 3
surface4.xlsx 4
surface5.xlsx 5
surface6.xlsx 6
surface7.xlsx 7
surface8

In [85]:
f[2]

array([0.7])

In [72]:
a[7]

array([0.03311325, 0.02154787, 0.02140756, ..., 0.44916707, 0.45036951,
       0.45083036])

In [89]:
k[5]

array([0], dtype=int64)